export const palettes = [
  {
    id: 'revenue-run' as const,
    name: 'Revenue Run',
    mode: 'light' as const,
    tokens: {
      '--color-cc-bg': '#F4F6FA',
      '--color-cc-surface-1': '#FFFFFF',
      '--color-cc-surface-2': '#EDF0F7',
      '--color-cc-surface-3': '#E0E4EF',
      '--color-cc-border': '#CDD3E0',
      '--color-cc-border-hover': '#A8B1C4',
      '--color-cc-text': '#141B2D',
      '--color-cc-text-secondary': '#4A5468',
      '--color-cc-text-muted': '#7C8598',
      '--color-cc-accent': '#4F46E5',
      '--color-cc-accent-hover': '#4338CA',
      '--color-cc-accent-fg': '#FFFFFF',
      '--color-cc-success': '#059669',
      '--color-cc-warning': '#D97706',
      '--color-cc-danger': '#DC2626',
      '--color-cc-info': '#0284C7',
    },
    chartColors: ['#4F46E5', '#059669', '#DC2626', '#D97706', '#0284C7', '#7C3AED'],
  },
  {
    id: 'peak-hour' as const,
    name: 'Peak Hour',
    mode: 'light' as const,
    tokens: {
      '--color-cc-bg': '#F0F7FF',
      '--color-cc-surface-1': '#FFFFFF',
      '--color-cc-surface-2': '#E8F0FE',
      '--color-cc-surface-3': '#D4E4FA',
      '--color-cc-border': '#B8CDE8',
      '--color-cc-border-hover': '#8BADD4',
      '--color-cc-text': '#0F1A2E',
      '--color-cc-text-secondary': '#3B4F6B',
      '--color-cc-text-muted': '#6B7FA0',
      '--color-cc-accent': '#2563EB',
      '--color-cc-accent-hover': '#1D4ED8',
      '--color-cc-accent-fg': '#FFFFFF',
      '--color-cc-success': '#059669',
      '--color-cc-warning': '#EA580C',
      '--color-cc-danger': '#DC2626',
      '--color-cc-info': '#0891B2',
    },
    chartColors: ['#2563EB', '#059669', '#DC2626', '#EA580C', '#0891B2', '#9333EA'],
  },
  {
    id: 'evening-rush' as const,
    name: 'Evening Rush',
    mode: 'dark' as const,
    tokens: {
      '--color-cc-bg': '#0B1120',
      '--color-cc-surface-1': '#111827',
      '--color-cc-surface-2': '#1E293B',
      '--color-cc-surface-3': '#293548',
      '--color-cc-border': '#334155',
      '--color-cc-border-hover': '#475569',
      '--color-cc-text': '#F1F5F9',
      '--color-cc-text-secondary': '#CBD5E1',
      '--color-cc-text-muted': '#94A3B8',
      '--color-cc-accent': '#22D3EE',
      '--color-cc-accent-hover': '#06B6D4',
      '--color-cc-accent-fg': '#0B1120',
      '--color-cc-success': '#34D399',
      '--color-cc-warning': '#FBBF24',
      '--color-cc-danger': '#F87171',
      '--color-cc-info': '#38BDF8',
    },
    chartColors: ['#22D3EE', '#34D399', '#F87171', '#FBBF24', '#38BDF8', '#A78BFA'],
  },
  {
    id: 'night-owl' as const,
    name: 'Night Owl',
    mode: 'dark' as const,
    tokens: {
      '--color-cc-bg': '#1A1423',
      '--color-cc-surface-1': '#211A2E',
      '--color-cc-surface-2': '#2D2440',
      '--color-cc-surface-3': '#3A3050',
      '--color-cc-border': '#4A3F60',
      '--color-cc-border-hover': '#6B5F88',
      '--color-cc-text': '#F5F0FF',
      '--color-cc-text-secondary': '#D4C8EF',
      '--color-cc-text-muted': '#A99BC8',
      '--color-cc-accent': '#F59E0B',
      '--color-cc-accent-hover': '#D97706',
      '--color-cc-accent-fg': '#1A1423',
      '--color-cc-success': '#34D399',
      '--color-cc-warning': '#FB923C',
      '--color-cc-danger': '#FB7185',
      '--color-cc-info': '#67E8F9',
    },
    chartColors: ['#F59E0B', '#34D399', '#FB7185', '#FB923C', '#67E8F9', '#C084FC'],
  },
] as const;

export type PaletteId = (typeof palettes)[number]['id'];
export type Palette = (typeof palettes)[number];

export function getPalette(id: PaletteId): Palette {
  return palettes.find((p) => p.id === id) ?? palettes[0];
}
