import LegalPageLayout from '../components/ui/LegalPageLayout';

const h2Style = {
  fontFamily: "'DM Serif Display', var(--font-dm-serif), serif",
  fontSize: 22,
  fontWeight: 400 as const,
  color: '#363840',
  marginTop: 40,
  marginBottom: 16,
};

const h3Style = {
  fontFamily: "'DM Sans', var(--font-dm-sans), sans-serif",
  fontSize: 16,
  fontWeight: 600 as const,
  color: '#363840',
  marginTop: 28,
  marginBottom: 10,
};

const pStyle = {
  fontSize: 15,
  lineHeight: 1.7,
  color: '#363840',
  marginBottom: 16,
};

const liStyle = {
  fontSize: 15,
  lineHeight: 1.7,
  color: '#363840',
  marginBottom: 8,
};

export default function TermsPage() {
  return (
    <LegalPageLayout>
      <h1
        style={{
          fontFamily: "'DM Serif Display', var(--font-dm-serif), serif",
          fontSize: 32,
          fontWeight: 400,
          color: '#1a1d23',
          marginBottom: 8,
        }}
      >
        Terms of Service
      </h1>
      <p style={{ fontSize: 14, color: '#6b6d74', marginBottom: 32 }}>
        <strong>Effective Date:</strong> February 28, 2026 &nbsp;&middot;&nbsp; <strong>Last Updated:</strong> February 28, 2026
      </p>

      <hr style={{ border: 'none', borderTop: '1px solid rgba(26,29,35,0.08)', margin: '24px 0' }} />

      <h2 style={h2Style}>1. Acceptance of Terms</h2>
      <p style={pStyle}>
        By accessing or using Parallax (&ldquo;the Software,&rdquo; &ldquo;the Service&rdquo;), a transit and trip service planning tool, you (&ldquo;User,&rdquo; &ldquo;you&rdquo;) agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree to these Terms, you must immediately discontinue use of the Software.
      </p>
      <p style={pStyle}>
        These Terms constitute a legally binding agreement between you and Parallax (&ldquo;we,&rdquo; &ldquo;us,&rdquo; &ldquo;our&rdquo;). Use of the Software constitutes acceptance of these Terms in their entirety.
      </p>

      <h2 style={h2Style}>2. Description of Service</h2>
      <p style={pStyle}>
        Parallax is a browser-based transit service planning tool that enables users to import route and trip data, analyze demand patterns, create route structures, and export run bids. The Software is designed for use by transit operations professionals and organizations for planning and analytical purposes.
      </p>
      <p style={pStyle}>
        The Software currently integrates with third-party mapping services, including Mapbox, and may incorporate additional features and integrations — including artificial intelligence and machine learning capabilities — in future releases.
      </p>

      <h2 style={h2Style}>3. Intended Use and Disclaimer of Operational Reliance</h2>
      <p style={{ ...pStyle, fontWeight: 600 }}>
        Parallax is provided for demonstration, educational, and planning-support purposes only.
      </p>
      <p style={pStyle}>
        The Software is not intended to serve as the sole basis for operational decisions affecting transit service delivery, public safety, labor allocation, regulatory compliance, or any other material business outcome. Any outputs generated by the Software — including but not limited to route structures, run bids, productivity metrics, on-time performance estimates, and demand analyses — are approximations intended to support, not replace, professional judgment.
      </p>
      <p style={{ ...pStyle, fontWeight: 600 }}>You acknowledge and agree that:</p>
      <ul style={{ paddingLeft: 24, marginBottom: 16 }}>
        <li style={liStyle}>The Software produces planning estimates and analytical outputs that may contain errors, inaccuracies, or omissions.</li>
        <li style={liStyle}>You bear sole responsibility for independently validating all outputs before applying them to live operations.</li>
        <li style={liStyle}>Parallax is not responsible for any decisions you make, or actions you take, based on information or outputs provided by the Software.</li>
        <li style={liStyle}>Parallax assumes no liability for operational disruptions, financial losses, service failures, regulatory penalties, labor disputes, or any other consequences arising from reliance on the Software&apos;s outputs.</li>
      </ul>

      <h2 style={h2Style}>4. Waiver of Right to Litigation</h2>
      <p style={{ ...pStyle, fontWeight: 600, textTransform: 'uppercase' as const, fontSize: 14 }}>
        BY USING THE SOFTWARE, YOU EXPRESSLY AND VOLUNTARILY WAIVE ANY AND ALL RIGHTS TO PURSUE LITIGATION — INCLUDING BUT NOT LIMITED TO INDIVIDUAL LAWSUITS, CLASS ACTIONS, AND COLLECTIVE ACTIONS — AGAINST PARALLAX, ITS OWNERS, OPERATORS, OFFICERS, EMPLOYEES, CONTRACTORS, AND AFFILIATES ARISING OUT OF OR RELATED TO YOUR USE OF THE SOFTWARE.
      </p>
      <p style={pStyle}>
        This waiver applies to claims of any kind, whether based in contract, tort, statute, regulation, negligence, strict liability, or any other legal or equitable theory, including but not limited to claims for direct, indirect, incidental, consequential, special, exemplary, or punitive damages.
      </p>
      <p style={pStyle}>
        If any dispute arises between you and Parallax relating to the Software, you agree that such dispute shall be resolved exclusively through binding arbitration administered under the rules of the American Arbitration Association, conducted in the State of Kansas. Each party shall bear its own costs and attorney&apos;s fees.
      </p>
      <p style={pStyle}>
        You acknowledge that by agreeing to this waiver, you are giving up your constitutional right to a trial by jury and your right to participate in a class or collective action.
      </p>

      <h2 style={h2Style}>5. Limitation of Liability</h2>
      <p style={{ ...pStyle, fontWeight: 600, textTransform: 'uppercase' as const, fontSize: 14 }}>
        TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, PARALLAX, ITS OWNERS, OPERATORS, OFFICERS, EMPLOYEES, AND CONTRACTORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, NOR FOR ANY LOSS OF PROFITS, REVENUE, DATA, GOODWILL, OR BUSINESS OPPORTUNITY, REGARDLESS OF THE CAUSE OF ACTION OR THEORY OF LIABILITY.
      </p>
      <p style={{ ...pStyle, fontWeight: 600, textTransform: 'uppercase' as const, fontSize: 14 }}>
        IN NO EVENT SHALL PARALLAX&apos;S TOTAL AGGREGATE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATED TO THE SOFTWARE EXCEED THE AMOUNT YOU HAVE PAID FOR USE OF THE SOFTWARE IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR TEN DOLLARS ($10.00), WHICHEVER IS GREATER.
      </p>

      <h2 style={h2Style}>6. No Warranty</h2>
      <p style={{ ...pStyle, fontWeight: 600, textTransform: 'uppercase' as const, fontSize: 14 }}>
        THE SOFTWARE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY. PARALLAX EXPRESSLY DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, RELIABILITY, TITLE, AND NON-INFRINGEMENT.
      </p>
      <p style={pStyle}>
        Parallax does not warrant that the Software will be uninterrupted, error-free, secure, or free of harmful components, or that any defects will be corrected. No advice or information obtained through the Software shall create any warranty not expressly stated in these Terms.
      </p>

      <h2 style={h2Style}>7. User Data and Responsibility</h2>
      <h3 style={h3Style}>7.1 Data You Provide</h3>
      <p style={pStyle}>
        Users are responsible for all data imported into or entered within the Software. The Software processes route, trip, and run data that users supply from their own operational systems.
      </p>
      <h3 style={h3Style}>7.2 Personally Identifiable Information (PII) and Protected Health Information (PHI)</h3>
      <p style={pStyle}>
        <strong>The Software is not designed to collect, store, or process PII or PHI.</strong> Users should take care to exclude PII and PHI from any data imported into the Software. If PII or PHI is inadvertently included in data you upload, you do so at your own risk. Parallax assumes no responsibility for the security or handling of PII or PHI that users introduce into the Software.
      </p>
      <h3 style={h3Style}>7.3 Session Data</h3>
      <p style={pStyle}>
        The Software uses token-based sessions to manage user workspaces. Session data — including imported trip and route data, settings, optimization parameters, run configurations, and import templates — is stored for the duration of the session and may be subject to periodic cleanup. Parallax makes no guarantee regarding the persistence or long-term availability of session data.
      </p>

      <h2 style={h2Style}>8. Third-Party Services</h2>
      <p style={pStyle}>
        The Software integrates with third-party services, including but not limited to Mapbox for mapping and geocoding functionality. Your use of such third-party services through the Software is subject to those providers&apos; respective terms of service and privacy policies. Parallax is not responsible for the availability, accuracy, or conduct of any third-party service.
      </p>

      <h2 style={h2Style}>9. Intellectual Property</h2>
      <p style={pStyle}>
        All rights, title, and interest in and to the Software — including its design, architecture, source code, visual elements, documentation, and all associated intellectual property — remain the exclusive property of Parallax and its operators. These Terms grant you no ownership interest in the Software and no license except the limited right to use the Software in accordance with these Terms.
      </p>

      <h2 style={h2Style}>10. Acceptable Use</h2>
      <p style={pStyle}>
        While the Company does not impose specific restrictions on the types of transit planning use cases for which the Software may be employed, you agree not to:
      </p>
      <ul style={{ paddingLeft: 24, marginBottom: 16 }}>
        <li style={liStyle}>Attempt to reverse engineer, decompile, disassemble, or otherwise derive the source code of the Software.</li>
        <li style={liStyle}>Use the Software to engage in any activity that violates applicable local, state, federal, or international law.</li>
        <li style={liStyle}>Interfere with, disrupt, or place an unreasonable burden on the Software&apos;s infrastructure.</li>
        <li style={liStyle}>Attempt to gain unauthorized access to any portion of the Software or its underlying systems.</li>
        <li style={liStyle}>Resell, sublicense, or redistribute access to the Software without prior written consent from Parallax.</li>
      </ul>

      <h2 style={h2Style}>11. Availability and Modification</h2>
      <p style={pStyle}>
        Parallax reserves the right to modify, suspend, or discontinue the Software — in whole or in part — at any time, with or without notice. Parallax shall not be liable to you or any third party for any modification, suspension, or discontinuation of the Software.
      </p>
      <p style={pStyle}>
        Parallax reserves the right to update these Terms at any time. Continued use of the Software following the posting of revised Terms constitutes acceptance of those changes. It is your responsibility to review these Terms periodically.
      </p>

      <h2 style={h2Style}>12. Indemnification</h2>
      <p style={pStyle}>
        You agree to indemnify, defend, and hold harmless Parallax, its owners, operators, officers, employees, contractors, and affiliates from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorney&apos;s fees) arising out of or related to your use of the Software, your violation of these Terms, or your violation of any applicable law or regulation.
      </p>

      <h2 style={h2Style}>13. Governing Law and Jurisdiction</h2>
      <p style={pStyle}>
        These Terms shall be governed by and construed in accordance with the laws of the State of Kansas and applicable federal law of the United States, without regard to conflict of law principles. To the extent any matter is not subject to the arbitration provisions of Section 4, the exclusive jurisdiction and venue for any legal proceedings shall be the state and federal courts located in the State of Kansas.
      </p>

      <h2 style={h2Style}>14. Severability</h2>
      <p style={pStyle}>
        If any provision of these Terms is found to be invalid, illegal, or unenforceable by a court of competent jurisdiction, such finding shall not affect the validity of the remaining provisions, which shall continue in full force and effect. The invalid provision shall be modified to the minimum extent necessary to make it valid and enforceable while preserving its original intent.
      </p>

      <h2 style={h2Style}>15. Entire Agreement</h2>
      <p style={pStyle}>
        These Terms, together with any Privacy Policy published by Parallax, constitute the entire agreement between you and Parallax with respect to the Software and supersede all prior or contemporaneous communications, proposals, and agreements, whether oral or written.
      </p>

      <h2 style={h2Style}>16. Contact</h2>
      <p style={pStyle}>
        For questions regarding these Terms, please contact:
      </p>
      <p style={pStyle}>
        <strong>Parallax</strong><br />
        Email: <a href="mailto:john@jroverton.com" style={{ color: '#2a6b5a' }}>john@jroverton.com</a>
      </p>

      <hr style={{ border: 'none', borderTop: '1px solid rgba(26,29,35,0.08)', margin: '32px 0 16px' }} />
      <p style={{ fontSize: 14, fontStyle: 'italic', color: '#6b6d74' }}>
        By using Parallax, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
      </p>
    </LegalPageLayout>
  );
}
